-- CreateEnum
CREATE TYPE "RewardType" AS ENUM ('ONE_MONTH_HOBBY_LICENSE');

-- CreateTable
CREATE TABLE "Referral" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "code" STRING NOT NULL,
    "user_uid" UUID NOT NULL,
    "referrer_id" INT4,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,
    "used" BOOL NOT NULL DEFAULT false,
    "available" BOOL NOT NULL DEFAULT false,

    CONSTRAINT "Referral_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ReferralReward" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "referral_id" INT4 NOT NULL,
    "reward" "RewardType" NOT NULL,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "ReferralReward_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Referral_code_key" ON "Referral"("code");

-- CreateIndex
CREATE UNIQUE INDEX "Referral_user_uid_key" ON "Referral"("user_uid");

-- CreateIndex
CREATE INDEX "Referral_referrer_id_idx" ON "Referral"("referrer_id");

-- CreateIndex
CREATE INDEX "Referral_code_idx" ON "Referral"("code");

-- CreateIndex
CREATE INDEX "Referral_user_uid_idx" ON "Referral"("user_uid");

-- CreateIndex
CREATE UNIQUE INDEX "Referral_user_uid_referrer_id_key" ON "Referral"("user_uid", "referrer_id");

-- CreateIndex
CREATE INDEX "ReferralReward_referral_id_idx" ON "ReferralReward"("referral_id");
